language: python
python:
  - "3.6"
sudo: false
git:
  depth: false
branches:
  only:
  - master
  - develop
install:
  - pip install -r scripts/requirements.txt
before_script:
  - chmod +x ./scripts/*.py
  - chmod +x ./scripts/deploy/*.sh
script:
  - python ./scripts/check_data.py
  - python ./scripts/build_data.py
deploy:
- provider: script
  script: bash scripts/deploy/deploy_staging.sh
  skip_cleanup: true
  on:
    branch: develop
- provider: script
  script: scripts/deploy/deploy.sh
  skip_cleanup: true
  on:
    branch: master
