language: python
python:
- '3.6'
sudo: false
git:
  depth: false
branches:
  only:
  - master
  - develop
install:
- pip install -r scripts/requirements.txt
before_script:
- chmod +x ./scripts/*.py
- chmod +x ./scripts/deploy/*.sh
script:
- python ./scripts/check_data.py
- python ./scripts/build_data.py
deploy:
- provider: script
  script: bash scripts/deploy/deploy_staging.sh
  skip_cleanup: true
  on:
    branch: develop
- provider: script
  script: scripts/deploy/deploy.sh
  skip_cleanup: true
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_25492e6fe4ee_key -iv $encrypted_25492e6fe4ee_iv
  -in keys.tar.enc -out keys.tar -d
env:
  global:
    secure: wFSoQi4yzDxqPAOjjpHX9weQLFV7gRdIbFS3WaBQSFGbsdYv1vP9TexvtdmArIH+qe87rgADaQjvmBsqJVJXZtAayAnFjVGdjIbpbiHeza4OiVEgD/ydQirdCv6Z58lFFAEgGKciXrOhOQme+Lk+H2B8mxUjl5UMXL3qxxhdNIj9PgzfgYXYisWQBgVOI8zVxv/BRnCriPvvdqre9piJmcmYOkybxshspDgbAc+02ObQWq4/V7WnG4Y4soh9+suoIbgNtRo2oO6en4JneQHlqX+2CW3H++TKlKvGqoPxPVXGGU7k4dND/1fXAJ0chA3k4KFU5xGK56EF5PGXXHyako5Cbaav+w+1D733wo/Nlbc8JcaOmYt7EjlUjJMfY8uVbsYf20G+bcwnWoPRKS7rDMOtGn8shLD8hA35RNu3Ig1HACwf9xyXLodvOEuULwXBiaELYuAGdsvB0IISn3hMuR6wz0PteWdT1Kw/ZriMxfOUQxLRKPXBMJM7jCRUeni7Uqe+jB/JIPVHReWfXmp3fv2XStEZWC7P4LquLKsm2uFbYOYo34kN208naAkCYhk31cpOFICR7sw40MJIdYI48lNyfekk+GbN9jhsiLGH+8OkygQv/ieRgq5LOhCRAEFAWOB8PC9F1nAouGtjKA6BuECXMvHEV6Q5P6d/D28oLT4=
